Search bar displaying results
lablueprint/trans-can-work pull request #13
Opened 2023-02-23 08:03 UTC by alannguyen711

Search bar displaying all the results of jobseekers based off of names.
Still need to display names alphabetically (if we are using this convention).
Will implement filtering next!
<3

2023-02-26 23:51 UTC, soliavalentine requested changes
Great job Alan!!! I am soso proud, and you have come so far! It was truly amazing to see your independence and problem solving skills grow during this sprint! The search functionality works perfectly, and there are just a couple of relatively small changes that we should make before merging:
- We want the results to return alphabetically. I don't think this should be too difficult, I think you should be able to just sort the array you are returning or alternatively the array of names that you pull from the backend before applying the search functionality
-  Because the your search functionality is a component and not going to be on its own page, we should move the functionality to the components folder! You can create a test page or use one of the other pages for testing
Once again great job Alan wooo!!

2023-02-28 06:30 UTC, alannguyen711 commented
Alphabetized the search results and moved everything into components!

2023-03-14 06:18 UTC, soliavalentine approved these changes

2023-03-14 06:18 UTC, soliavalentine commented
One thing—Before merging please test out the new versions of fetch on jobseekers on main!

2023-04-04 05:40 UTC, merged