Profile button
lablueprint/trans-can-work pull request #16
Opened 2023-03-14 05:54 UTC by kaeleytran

- profile button that displays name, field of work, and link to profile page of jobseeker passed through props 
- can archive, bookmark, or delete user 
- when a user is archived, can only unarchive or delete user and button changes color

2023-03-27 03:40 UTC, soliavalentine requested changes
Great job Kaylee! This component looks really good and just needs a bit of cleanup to be ready to merge! Specifically:
- Remove unused comments/code and console.log statements
- Remove the navigator dashboard component since we ended up using kevins! (I think what may have happened is that you created a new branch off of your old branch rather than from main. In that case, I think that the easiest thing to do would be to pull from main and create a new branch and add your changes there.)
- I am a little unsure how to test your component. Maybe you could show me a demo with a jobseeker on monday!
-  I think the designers want there to be an icon to indicate whether or not a given jobseeker has been bookmarked, so it would be great if you could add this functionality!
- Lastly, since we want this component to be used for both jobseekers and navigators, we need to check if the user passed in is a navigator or jobseeker to see if we should display the archive feature!
I know this is a lot so please let me know if you have any questions, but once again great job!

2023-03-27 03:40 UTC, soliavalentine commented on src/App.js
> +        <Route path="/navigatordashboard" element={<NavigatorDashboard />} />
can we remove this route? It routes to the same place as /dashboard/navigator

2023-03-27 03:40 UTC, soliavalentine commented on src/Components/navigatorDashboard.js
> +      //   name: query.data()["name"],
we can remove this the jobseeker info is set in the assessment

2023-03-27 03:40 UTC, soliavalentine commented on src/Components/navigatorDashboard.js
> +    {/* <Button onClick={onJobseekerClick} style={{ width: "100px", height:"50px",borderColor: 'grey', text:"client af" }} >jobseeker af</Button> */}
please remove unused comments

2023-03-27 03:40 UTC, soliavalentine commented on src/Components/navigatorDashboard.js
> +            <h3>{seeker.name}</h3>
unused comment?

2023-03-27 03:40 UTC, soliavalentine commented on src/Components/navigatorDashboard.js
I think this component is virtually the same as kevin's navigatordashboard page if I'm not mistaken. If so I think we can remove this and just use the preexisting page!

2023-03-27 03:40 UTC, soliavalentine commented on src/Components/profileButton.js
> +// import ListItemIcon from '@mui/material/ListItemIcon';
please remove unused comments

2023-03-27 03:40 UTC, soliavalentine commented on src/Components/profileButton.js
When I test your component I don't see a difference in color when I attempt to archive, bookmark or delete. Is there a way I can test that functionality?

2023-04-04 04:29 UTC, kaeleytran commented on src/Components/profileButton.js
i think it should auto update???let me test again to make sure

2023-04-09 23:25 UTC, closed without merging